apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
patchesStrategicMerge:
  - config-map.yaml

images:
  - name: apirator
    newName: apirator/apirator-backend:0.0.1
    newTag: latest