apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apirator-backend-cluster-role
rules:
  - apiGroups: [""]
    resources:
      - configmaps
      - endpoints
      - namespaces
      - nodes
      - pods
      - pods/log
      - replicationcontrollers
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "apirator.io"
    resources:
      - apimocks
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch