apiVersion: v1
kind: Service
metadata:
  name: apirator-backend-service
spec:
  type: ClusterIP
  ports:
    - port: 9999
      targetPort: 9999
      protocol: TCP
      name: http
  selector:
    app: apirator-backend
